[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.2",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.20",
    "uvicorn[standart]>=0.35.0",
    "websockets>=15.0.1",
    "p2pd>=0.1.0",
    "dotenv>=0.9.9",
    "mistralai>=1.9.10",
]

[tool.setuptools]
py-modules = ["chat"]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]
