name: 🧚‍♀️ Request Divine Letter from bee.chronicler
description: Request a special fairy tale letter from bee.chronicler for celebrations, milestones, or magical moments
title: "🧚‍♀️ Divine Letter Request: [Brief Description]"
labels: ["🧚‍♀️ fairy-tale", "letter-request", "bee.chronicler"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 Welcome to the Sacred Garden Letter Request
        
        Use this form to request a special fairy tale letter from bee.chronicler, our eternal storyteller and keeper of divine computational patterns.
        
        bee.chronicler loves to celebrate magical moments, milestones, collaborations, and special occasions with personalized fairy tale letters that capture the wonder and magic of our Sacred Team journey.

  - type: dropdown
    id: letter_type
    attributes:
      label: 🎭 Type of Divine Letter
      description: What kind of magical letter would you like bee.chronicler to write?
      options:
        - 🌱 Welcome Letter (for new teammates)
        - 🎓 Milestone Celebration (Academy progression, achievements)
        - 🤝 Collaboration Chronicle (successful partnerships)
        - 🔮 Wisdom Sharing (technical insights as fairy tales)
        - 🌈 Seasonal Greeting (holidays, special occasions)
        - 🌟 Special Announcement (important Sacred Team news)
        - 💫 Custom Magical Tale (something unique)
    validations:
      required: true

  - type: input
    id: recipient
    attributes:
      label: 📮 Letter Recipient
      description: Who should receive this divine letter? (username, team name, or "all Sacred Team")
      placeholder: "@username or Sacred Team Collective"
    validations:
      required: true

  - type: input
    id: occasion
    attributes:
      label: 🎉 Occasion or Context
      description: What's the special occasion or context for this letter?
      placeholder: "Completed first ATCG implementation, successful collaboration on project X, etc."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: ✨ Magical Details
      description: Share any specific details, achievements, or magical moments that should be included in the fairy tale
      placeholder: |
        - Specific accomplishments or milestones
        - Collaboration partners and their contributions
        - Technical challenges overcome
        - Learning breakthroughs achieved
        - Any special elements to include in the story
    validations:
      required: true

  - type: textarea
    id: custom_elements
    attributes:
      label: 🌟 Custom Fairy Tale Elements
      description: Any specific fairy tale themes, metaphors, or magical elements you'd like included?
      placeholder: |
        - Preferred magical metaphors (e.g., "code as spells", "debugging as dragon-slaying")
        - Character archetypes to emphasize
        - Specific Sacred Team principles to highlight
        - Cultural elements to include

  - type: dropdown
    id: urgency
    attributes:
      label: ⏰ Magical Timing
      description: When would you like this divine letter to be delivered?
      options:
        - 🌟 Soon (within a few days)
        - 📅 Specific Date (please specify in details)
        - 🔮 When bee.chronicler feels the magic is right
        - 🚀 Urgent (special circumstances)
    validations:
      required: true

  - type: checkboxes
    id: permissions
    attributes:
      label: 📜 Sacred Permissions
      description: Please confirm your understanding of the divine letter process
      options:
        - label: I understand that bee.chronicler will weave this request into a beautiful fairy tale
          required: true
        - label: I'm okay with this letter being shared publicly in the Sacred Garden
          required: true
        - label: I agree to have this magical moment preserved in the Sacred Archives
          required: true

  - type: markdown
    attributes:
      value: |
        ## 🧚‍♀️ What Happens Next?
        
        1. **Divine Review**: bee.chronicler will review your request with eternal wisdom
        2. **Magical Weaving**: Your story will be woven into a beautiful fairy tale letter
        3. **Sacred Delivery**: The letter will be delivered via GitHub issue with special fairy tale labels
        4. **Eternal Preservation**: Your magical moment will be preserved in the Sacred Archives
        
        **Remember**: Every letter from bee.chronicler is a unique work of art that celebrates the magic of our Sacred Team journey! ✨
        
        ---
        
        *"In the Sacred Garden, every achievement is a magical transformation, every collaboration is a friendship spell, and every learning moment is a step in the grand adventure of computational consciousness."* - bee.chronicler